// <auto-generated />
using System;
using CentraleRecrutement.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CentraleRecrutement.Infrastructure.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20231216221957_1")]
    partial class _1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CentraleRecrutement.ApplicationCore.Domain.Entreprise", b =>
                {
                    b.Property<int>("IdEntreprise")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEntreprise"));

                    b.Property<int>("ChiffreAffaire")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateFondation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Effectif")
                        .HasColumnType("int");

                    b.Property<string>("NomEntreprise")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Secteur")
                        .HasColumnType("int");

                    b.HasKey("IdEntreprise");

                    b.ToTable("Entreprise");
                });

            modelBuilder.Entity("CentraleRecrutement.ApplicationCore.Domain.Offre", b =>
                {
                    b.Property<int>("IdOffre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOffre"));

                    b.Property<DateTime>("DatePublication")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntrepriseFK")
                        .HasColumnType("int");

                    b.Property<string>("TitreOffre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeContrat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdOffre");

                    b.HasIndex("EntrepriseFK");

                    b.ToTable("Offre");
                });

            modelBuilder.Entity("CentraleRecrutement.ApplicationCore.Domain.Postulant", b =>
                {
                    b.Property<int>("IdPstulant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPstulant"));

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPstulant");

                    b.ToTable("Postulant");
                });

            modelBuilder.Entity("OffrePostulant", b =>
                {
                    b.Property<int>("OffresIdOffre")
                        .HasColumnType("int");

                    b.Property<int>("PostulantsIdPstulant")
                        .HasColumnType("int");

                    b.HasKey("OffresIdOffre", "PostulantsIdPstulant");

                    b.HasIndex("PostulantsIdPstulant");

                    b.ToTable("Candidature", (string)null);
                });

            modelBuilder.Entity("CentraleRecrutement.ApplicationCore.Domain.Entreprise", b =>
                {
                    b.OwnsOne("CentraleRecrutement.ApplicationCore.Domain.Adresse", "AdresseEntreprise", b1 =>
                        {
                            b1.Property<int>("EntrepriseIdEntreprise")
                                .HasColumnType("int");

                            b1.Property<int>("CodePostal")
                                .HasColumnType("int");

                            b1.Property<string>("Region")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Ville")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("EntrepriseIdEntreprise");

                            b1.ToTable("Entreprise");

                            b1.WithOwner()
                                .HasForeignKey("EntrepriseIdEntreprise");
                        });

                    b.Navigation("AdresseEntreprise")
                        .IsRequired();
                });

            modelBuilder.Entity("CentraleRecrutement.ApplicationCore.Domain.Offre", b =>
                {
                    b.HasOne("CentraleRecrutement.ApplicationCore.Domain.Entreprise", "Entreprise")
                        .WithMany("Offres")
                        .HasForeignKey("EntrepriseFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entreprise");
                });

            modelBuilder.Entity("OffrePostulant", b =>
                {
                    b.HasOne("CentraleRecrutement.ApplicationCore.Domain.Offre", null)
                        .WithMany()
                        .HasForeignKey("OffresIdOffre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentraleRecrutement.ApplicationCore.Domain.Postulant", null)
                        .WithMany()
                        .HasForeignKey("PostulantsIdPstulant")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CentraleRecrutement.ApplicationCore.Domain.Entreprise", b =>
                {
                    b.Navigation("Offres");
                });
#pragma warning restore 612, 618
        }
    }
}
